apiVersion: v2
name: todo
description: A Helm chart for TODO application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - todo
  - microservice
  - redis
home: https://github.com/your-org/todo-app
sources:
  - https://github.com/your-org/todo-app
maintainers:
  - name: DevOps Team
    email: devops@yourcompany.com
dependencies:
  - name: redis
    version: "18.1.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled