# Development environment values
replicaCount: 1

image:
  repository: todo-app
  tag: latest
  pullPolicy: Always

config:
  nodeEnv: development
  logLevel: debug

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  hosts:
    - host: todo-dev.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

redis:
  enabled: true
  auth:
    enabled: true
    password: "dev-redis-password"
  master:
    persistence:
      enabled: false
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

monitoring:
  enabled: true
  serviceMonitor:
    enabled: false  # Disabled in dev for simplicity