apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo.fullname" . }}-config
  labels:
    {{- include "todo.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  PORT: {{ .Values.config.port | quote }}