apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.13.2
    helm:
      parameters:
        - name: fullnameOverride
          value: sealed-secrets-controller
        - name: resources.limits.cpu
          value: 100m
        - name: resources.limits.memory
          value: 128Mi
        - name: resources.requests.cpu
          value: 50m
        - name: resources.requests.memory
          value: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false